plugins {
    id 'java'
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.18"
    id("xyz.jpenilla.run-paper") version "3.0.2"
}

group = 'com.mrbysco'
version = "${version}"
base {
    archivesName = "${mod_name}"
}
description = "A paper plugin that allows clients to use Armor Poser to pose armor stands"

java {
    // Configure the java toolchain. This allows gradle to auto-provision JDK 21 on systems that only have JDK 11 installed for example.
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paper_version}"
    paperweight.paperDevBundle("${paperweight_version}")
}

tasks {
    compileJava {
        options.release = 21
    }
    runServer {
        minecraftVersion("${mc_version}")
        jvmArgs("-Xms2G", "-Xmx2G")
    }
}

processResources {
    def props = [version: version]
    getInputs().properties(props)
    filteringCharset("UTF-8")
    filesMatching("plugin.yml") {
        expand(props)
    }
}