# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Base info
mc_version=26.2
paper_version=26.2.build.+
paperweight_version=26.2.build.+

#Publishing
mod_name=ArmorPoser-Plugin
curseforge_id=1078242
modrinth_id=ZuV7Ztiw

# Version
plugin_version=2.1.0